version: '3.8'

services:
  chtime:
    # Use the pre-built image from Docker Hub or GitHub Container Registry
    # Replace 'your-username/chtime' with your actual image name
    image: your-username/chtime:latest
    container_name: chtime-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Nginx reverse proxy with SSL
  # nginx:
  #   image: nginx:alpine
  #   container_name: chtime-nginx
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - chtime
  #   restart: unless-stopped
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.chtime.rule=Host(`your-domain.com`)"
  #     - "traefik.http.routers.chtime.tls.certresolver=letsencrypt" 